### ISSUE TITLE
Use atlas for database migration

### ISSUE THREAD

**Issue by pseudoyu** [RSS3-Network/Node#216]
### What feature is it?

Integrate atlas for database migration

### What problem does this feature solve?

Database migration

### This is not a duplicated feature request or new worker proposal

- [x] I have searched [existing issues](https://github.com/rss3-network/node/issues) to ensure this feature has not already been requested and this is not a [New Worker](https://github.com/rss3-network/node/issues/new?assignees=&labels=worker&projects=&template=worker_coverage.yml).

**Comment by HenryQW** [comment]
Closed as not 100% feasible.
