### ISSUE TITLE
Set `block_start` based on Node's version, and purge historical data

### ISSUE THREAD

**Issue by HenryQW** [RSS3-Network/Node#336]
### What feature is it?

Each Node's version should have a list of `block_start` for all workers.

### What problem does this feature solve?

- Reduce the cost of operating a Node by purging historical data
- Make all Nodes consistent (data coverage)

### Additional description

<img width="1446" alt="image" src="https://github.com/RSS3-Network/Node/assets/5896343/d9d33a3c-3000-4f22-92b2-15790dd2c207">

**Comment by brucexc** [comment]
It also includes some configuration information that changes with node version variations. For instance, the current version supports networks and workers along with their corresponding configuration information.

**Comment by pseudoyu** [comment]
Now, `block_start` will pull from VSL to maintain consistency.
