### ISSUE TITLE
Simplify worker development logic

### ISSUE THREAD

**Issue by HenryQW** [RSS3-Network/Node#337]
### What feature is it?

Greatly simplify the development process for adding a new worker.

### What problem does this feature solve?

Currently, adding a new worker may require thousands of lines of code, which is not great for attracting developers.
We may need to restructure the relevant logic to reduce the amount of work required to add a new worker.
Some possible ways:
1. a CLI (TUI https://github.com/charmbracelet/bubbletea) to scaffold everything necessary for a worker, from folder directory to abigen, funcs to be implemented etc.
2. decouple as much as logic possible from the current engine.Worker interface.

### This is not a duplicated feature request or new worker proposal

- [X] I have searched [existing issues](https://github.com/rss3-network/node/issues) to ensure this feature has not already been requested and this is not a [New Worker](https://github.com/rss3-network/node/issues/new?assignees=&labels=worker&projects=&template=worker_coverage.yml).

**Comment by pseudoyu** [comment]
Refer to: <https://docs.rss3.io/guide/dsl/worker/contributing-a-new-worker-to-node>
