### ISSUE TITLE
Integrate Activity-Pub Protocol into RSS3 Node for Protocol Data Collection and Processing

### ISSUE THREAD

**Issue by FrankLi123** [RSS3-Network/Node#349]
### What feature is it?

The feature is the integration of the Activity-Pub protocol into the RSS3 Node, enabling it to collect and process data using this protocol.

### What problem does this feature solve?

This feature can solve issues about interoperability between RSS3 Node and some decentralized social networks that follow the Activity-Pub protocol. 

### This is not a duplicated feature request or new worker proposal

- [X] I have searched [existing issues](https://github.com/rss3-network/node/issues) to ensure this feature has not already been requested and this is not a [New Worker](https://github.com/rss3-network/node/issues/new?assignees=&labels=worker&projects=&template=worker_coverage.yml).

**Comment by FrankLi123** [comment]
Implement a **Mastodon-plugin** to help RSS3 Node operator send received ActivityPub data to the Node.

**Comment by brucexc** [comment]
Issue resolved by https://github.com/RSS3-Network/Node/pull/600
