### ISSUE TITLE
Retrieve network configuration parameters from VSL instead of hardcoding them

### ISSUE THREAD

**Issue by pseudoyu** [RSS3-Network/Node#402]
### What feature is it?

1. set config to vsl using scripts
2. retrieve network configuration parameters from VSL
3. reload workers at each epoch if any change

### What problem does this feature solve?

Hard-coded configurations complicate the process of updating nodes.

### This is not a duplicated feature request or new worker proposal

- [X] I have searched [existing issues](https://github.com/rss3-network/node/issues) to ensure this feature has not already been requested and this is not a [New Worker](https://github.com/rss3-network/node/issues/new?assignees=&labels=worker&projects=&template=worker_coverage.yml).

**Comment by brucexc** [comment]
Hi, I noticed that you are already working on this issue. I would like to know what the process is for retrieving network configuration parameters from the VSL?

**Comment by pseudoyu** [comment]
For now the designed process is:

1. Raise a REP to initiate or modify the configurations, such as the start block, network tolerance, etc.
2. Set the parameters in the NetworkParams contract on the VSL mainnet (ensure it is a valid JSON file).
3. When a node runs, restarts, or an epoch changes, the node will pull the latest configurations by invoking the NetworkParams contract on VSL. If there are changes, the related services will apply the new configurations.

Any problems or suggestions?

**Comment by brucexc** [comment]
> For now the designed process is:
> 
> 1. Raise a REP to initiate or modify the configurations, such as the start block, network tolerance, etc.
> 2. Set the parameters in the NetworkParams contract on the VSL mainnet (ensure it is a valid JSON file).
> 3. When a node runs, restarts, or an epoch changes, the node will pull the latest configurations by invoking the NetworkParams contract on VSL. If there are changes, the related services will apply the new configurations.
> 
> Any problems or suggestions?


Thank you for your prompt reply. I have a couple of questions:

1. After the REP is approved, at what point will the network configuration be updated?
2. After the network configuration is updated, will the nodes in the network immediately start using the new settings?

**Comment by pseudoyu** [comment]
1. The REP will specify the epoch when the parameter modification will take effect, and will set the parameters at the target time (through service or scripts).
2. The node will consistently pull the latest configuration from the VSL contract. If any changes are detected, it will apply the new settings immediately.

I'm also considering incorporating parameter version control (maybe an epoch -> config map strcuct) in the contract, allowing us to decide more flexibly when changes take effect.

**Comment by brucexc** [comment]
> 1. The REP will specify the epoch when the parameter modification will take effect, and will set the parameters at the target time (through service or scripts).
> 2. The node will consistently pull the latest configuration from the VSL contract. If any changes are detected, it will apply the new settings immediately.
> 
> I'm also considering incorporating parameter version control (maybe an epoch -> config map strcuct) in the contract, allowing us to decide more flexibly when changes take effect.
> 
> any ideas?


The timing of updating network configurations through scripts is crucial because nodes will immediately capture event logs related to changes in network settings and update their local configurations accordingly. This process seems feasible for now.
